@startuml

start

:input;

if (Genotyping) then (no)
    :Read count on raw BAM \n (mosaic count);
    :Normalization \n (normalize.R);

    :Single segmentation \n (mosaic segment);
    :Joint segmentation \n (mosaic segment);

    :SCE detection;

else (yes)
    :Re-genotyping \n (Freebayes);
endif
:Haplotype phasing \n (StrandPhaseR);
:Haplotagging \n (Whatshap);
:Read count on haplotaged BAM \n (mosaic count);

:SV calling;




stop
@enduml