FROM condaforge/miniforge3:latest
LABEL io.github.snakemake.containerized="true"
LABEL io.github.snakemake.conda_env_hash="1cddebade6bb7a9bef67630a8a2e51970cf695b7b9576d79d87bbc99e8b33a42"
LABEL org.opencontainers.image.description="MosaiCatcher Pipeline base image with all conda environments (mc_base, mc_bioinfo_tools, rtools, scNOVA). Assembly-specific BSgenome packages not included."

# Step 2: Retrieve conda environments

# Conda environment:
#   source: workflow/envs/mc_base.yaml
#   prefix: /conda-envs/5779be0fdcb83243309236d7b8551c11
#   name: mc-base
#   channels:
#     - conda-forge
#     - bioconda
#   dependencies:
#     - ashleys-qc
#     - bwa
#     - intervaltree
#     - matplotlib
#     - mosaicatcher
#     - multiqc
#     - pandas
#     - parmap
#     - perl
#     - pybigwig
#     - pypdf2
#     - pysam
#     - pytables
#     - pyyaml
#     - python=3.10
#     - rsync
#     - sambamba
#     - samtools
#     - scikit-learn=1.2.2
#     - scipy
#     - seaborn
#     - tabix
#     - tqdm
#     - xopen
RUN mkdir -p /conda-envs/5779be0fdcb83243309236d7b8551c11
COPY workflow/envs/mc_base.yaml /conda-envs/5779be0fdcb83243309236d7b8551c11/environment.yaml

# Conda environment:
#   source: workflow/envs/mc_bioinfo_tools.yaml
#   prefix: /conda-envs/3afe2bebce5cf5fcd9f74d5f84aa3c10
#   name: mc-bioinfo-tools
#   channels:
#     - conda-forge
#     - bioconda
#   dependencies:
#     - bcftools
#     - bedtools
#     - biobambam
#     - freebayes
#     - mosaicatcher
#     - samtools
#     - tabix
#     - whatshap
RUN mkdir -p /conda-envs/3afe2bebce5cf5fcd9f74d5f84aa3c10
COPY workflow/envs/mc_bioinfo_tools.yaml /conda-envs/3afe2bebce5cf5fcd9f74d5f84aa3c10/environment.yaml

# Conda environment:
#   source: workflow/envs/rtools.yaml
#   prefix: /conda-envs/de34670da0318c018e75c8dfd9317ed6
#   name: rtools
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - bioconductor-biocparallel
#     - bioconductor-breakpointr
#     - bioconductor-bsgenome
#     - bioconductor-complexheatmap
#     - bioconductor-edger
#     - bioconductor-genomicalignments
#     - bioconductor-genomicranges
#     - bioconductor-rsamtools
#     - fonts-conda-forge
#     - r-assertthat
#     - r-base
#     - r-biocmanager
#     - r-cairo
#     - r-cowplot
#     - r-data.table
#     - r-devtools
#     - r-doparallel
#     - r-dplyr
#     - r-foreach
#     - r-ggbeeswarm
#     - r-ggnewscale
#     - r-ggplot2
#     - r-ggpubr
#     - r-gplots
#     - r-gtools
#     - r-mc2d
#     - r-optparse
#     - r-pheatmap
#     - r-r.utils
#     - r-rcolorbrewer
#     - r-reshape
#     - r-reshape2
#     - r-scales
#     - r-stringi=1.7.12
#     - r-stringr
#     - r-tidyr
#     - strandphaser
RUN mkdir -p /conda-envs/de34670da0318c018e75c8dfd9317ed6
COPY workflow/envs/rtools.yaml /conda-envs/de34670da0318c018e75c8dfd9317ed6/environment.yaml

# Conda environment:
#   source: workflow/envs/scNOVA/scNOVA_DL.yaml
#   prefix: /conda-envs/1500b5655a7c1aa812aa710896ca7666
#   name: scNOVA_DL
#   channels:
#     - conda-forge
#     - anaconda
#   dependencies:
#     - h5py=2.10.0
#     - matplotlib=3.1.1
#     - numpy
#     - pandas=0.25.3
#     - python=3.7.4
#     - scikit-learn=0.21.3
#     - tensorflow=1.15.0
#     - unzip
#     - pip:
#         - cffi
RUN mkdir -p /conda-envs/1500b5655a7c1aa812aa710896ca7666
COPY workflow/envs/scNOVA/scNOVA_DL.yaml /conda-envs/1500b5655a7c1aa812aa710896ca7666/environment.yaml

# Conda environment:
#   source: workflow/envs/scNOVA/scNOVA_R.yaml
#   prefix: /conda-envs/e4c4fbc0d8d5fdeeb1f51bb8c0e86716
#   name: scNOVA
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.3
#     - bioconductor-chromvar=1.12.0
#     - bioconductor-deseq2=1.30.0
#     - bioconductor-jaspar2016=1.18.0
#     - bioconductor-motifmatchr=1.12.0
#     - r-codetools=0.2_18
#     - r-doparallel
#     - r-factoextra=1.0.7
#     - r-fitdistrplus
#     - r-foreach
#     - r-gplots=3.1.1
#     - r-matrixstats=0.58.0
#     - r-nabor=0.5.0
#     - r-pheatmap=1.0.12
#     - r-pracma=2.3.3
#     - r-rtsne=0.15
#     - r-umap=0.2.7.0
RUN mkdir -p /conda-envs/e4c4fbc0d8d5fdeeb1f51bb8c0e86716
COPY workflow/envs/scNOVA/scNOVA_R.yaml /conda-envs/e4c4fbc0d8d5fdeeb1f51bb8c0e86716/environment.yaml

# Step 3: Generate conda environments

RUN conda env create --prefix /conda-envs/5779be0fdcb83243309236d7b8551c11 --file /conda-envs/5779be0fdcb83243309236d7b8551c11/environment.yaml && \
    conda env create --prefix /conda-envs/3afe2bebce5cf5fcd9f74d5f84aa3c10 --file /conda-envs/3afe2bebce5cf5fcd9f74d5f84aa3c10/environment.yaml && \
    conda env create --prefix /conda-envs/de34670da0318c018e75c8dfd9317ed6 --file /conda-envs/de34670da0318c018e75c8dfd9317ed6/environment.yaml && \
    conda env create --prefix /conda-envs/1500b5655a7c1aa812aa710896ca7666 --file /conda-envs/1500b5655a7c1aa812aa710896ca7666/environment.yaml && \
    conda env create --prefix /conda-envs/e4c4fbc0d8d5fdeeb1f51bb8c0e86716 --file /conda-envs/e4c4fbc0d8d5fdeeb1f51bb8c0e86716/environment.yaml && \
    conda clean --all -y
