# Assembly-specific Dockerfile for hg38
# Extends base image with BSgenome.Hsapiens.UCSC.hg38

FROM mosaicatcher:base

LABEL assembly="hg38"
LABEL bsgenome="BSgenome.Hsapiens.UCSC.hg38"

# Install BSgenome for hg38 via BiocManager
RUN /opt/conda/bin/Rscript -e 'BiocManager::install("BSgenome.Hsapiens.UCSC.hg38", update = FALSE, ask = FALSE)'

# Verify installation
RUN /opt/conda/bin/Rscript -e 'library(BSgenome.Hsapiens.UCSC.hg38); print(BSgenome.Hsapiens.UCSC.hg38)'
