name: MosaiCatcher basic checks with snakemake v9

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  Testing-basic-v8:
    runs-on: ubuntu-latest
    # needs:
    #   - Formatting
    #   - Linting
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # lfs: true

      - name: Git Submodule Update
        run: |
          # git pull --recurse-submodules
          git submodule update --remote --recursive --force --init

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: List contents of .tests
        run: |
          tree -h .tests

      - name: Show config file
        run: |
          cat .tests/config/simple_config_mosaicatcher.yaml

      - name: List contents of workflow/data
        run: |
          tree -h workflow/data

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: |
          mamba create -n snakemake_env -c conda-forge -c bioconda snakemake snakemake-storage-plugin-http
          mamba activate snakemake_env
          
      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --sdm conda --configfile .tests/config/simple_config_mosaicatcher.yaml \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile
